# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---



---
include:

  ### SOFLEV2 START ###

  # Sofle V2 - nice_nano_v2 + OLED
  - board: nice_nano_v2
    shield: sofle_left nice_oled
    cmake-args: >
      -DCONFIG_ZMK_KEYBOARD_NAME=\"Sofle_Oled\"
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_ZMK_SLEEP=y
      -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_left_oled
    snippet: studio-rpc-usb-uart

  - board: nice_nano_v2
    shield: sofle_right nice_oled
    cmake-args: >
      -DCONFIG_ZMK_SLEEP=y
      -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_right_oled

  # Sofle V2 - peripheral left
  - board: nice_nano_v2
    shield: sofle_left_peripheral nice_oled
    cmake-args: >
      -DCONFIG_ZMK_SLEEP=y
      -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_left_peripheral_oled
    
  - board: nice_nano_v2
    shield: settings_reset

  ### SOFLEV2 END ###


